#!/usr/bin/env node

import { Command } from "commander";
import fs from "fs";
import { OpenAPISpec } from "../lib/schema.ts";
import yaml from "js-yaml";
import generate from "./generate.ts";

const program = new Command();

program
  .name("openapi-typescript-server")
  .description("CLI to generate Open API server stub")
  .version("0.0.1") // TODO: How to align this with the package.json version?
  .argument("<spec>", "Path to Open API spec file")
  .description("Output generated code")
  .option(
    "-t, --types <types>",
    "Import path (relative to generated output) for type schema generated by open-api-typescript",
  )
  .option("-o, --output <dir>", "output directory", "")
  .action(async (spec, options) => {
    let specS = "";
    try {
      specS = fs.readFileSync(spec, "utf-8");
    } catch (e) {
      console.error("Error reading spec file", (e as Error).message);
      process.exit(1);
    }

    const specPojo = yaml.load(specS) as Map<string, any>;

    const validateSpecResponse = OpenAPISpec.safeParse(specPojo);

    if (!validateSpecResponse.success) {
      console.error(validateSpecResponse.error.errors);
      return;
    }

    const sourceFile = generate(
      validateSpecResponse.data,
      options.types,
      options.output,
    );

    if (options.output) {
      sourceFile.saveSync();
      return;
    }

    console.log(sourceFile.print());
  });

program.parse();
