openapi: 3.0.2
info:
  title: Simple Petstore
  version: 0.0.1
servers:
  - url: /api/v3
paths:
  /pets:
    get:
      operationId: listPets
      summary: Returns all pets from the system that the user has access to
      responses:
        "200":
          description: A list of pets.
          content:
            application/json:
              schema:
                type: object
                properties:
                  pets:
                    type: array
                    items:
                      $ref: "#/components/schemas/Pet"
        "default":
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /pet/{petId}:
    get:
      operationId: getPetById
      parameters:
        - name: petId
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  pet:
                    $ref: "#/components/schemas/Pet"
        "default":
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    post:
      operationId: updatePetWithForm
      parameters:
        - name: petId
          in: path
          description: ID of pet that needs to be updated
          required: true
          schema:
            type: integer
        - name: name
          in: query
          description: Name of pet that needs to be updated
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePetInput"
          application/xml:
            schema:
              $ref: "#/components/schemas/UpdatePetInput"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/UpdatePetInput"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  pet:
                    $ref: "#/components/schemas/Pet"
        "default":
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /pet/{petId}/mixed-content-types:
    post:
      operationId: mixedContentTypes
      parameters:
        - name: petId
          in: path
          description: ID of pet that needs to be updated
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jsonstatus:
                  type: string
                  enum:
                    - available
                    - pending
                    - sold
              required:
                - jsonstatus
          application/xml:
            schema:
              type: object
              properties:
                xmlstatus:
                  type: string
                  enum:
                    - available
                    - pending
                    - sold
              required:
                - xmlstatus
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  pet:
                    $ref: "#/components/schemas/Pet"
        "default":
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /pet/{petId}/image:
    get:
      operationId: getPetImage
      parameters:
        - name: petId
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
  /pet/{petId}/webpage:
    get:
      operationId: getPetWebpage
      parameters:
        - name: petId
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            text/html:
              schema:
                type: string
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
    Pet:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          $ref: "#/components/schemas/Category"
        photoUrls:
          type: array
          items:
            type: string
        tags:
          type: array
          items:
            $ref: "#/components/schemas/Tag"
        status:
          type: string
          description: pet status in the store
          enum:
            - available
            - pending
            - sold
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    UpdatePetInput:
      type: object
      properties:
        status:
          type: string
          enum:
            - available
            - pending
            - sold
      required:
        - status
